# Generated by Django 4.2.3 on 2024-09-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='entidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.entidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('OPERADOR', 'Operador'), ('QLOUDYX', 'Qloudyx')], max_length=50),
        ),
    ]
