# Generated by Django 4.2.3 on 2024-09-18 16:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_usuarios_entidade_alter_usuarios_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('QLOUDYX', 'Qloudyx'), ('CLIENTE', 'Cliente'), ('OPERADOR', 'Operador')], max_length=50),
        ),
    ]
