# Generated by Django 4.2.3 on 2024-09-18 16:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_usuarios_telefone_alter_usuarios_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
