# Generated by Django 4.2.3 on 2024-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_usuarios_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/uploads/fotos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('OPERADOR', 'Operador'), ('CLIENTE', 'Cliente'), ('QLOUDYX', 'Qloudyx')], max_length=50),
        ),
    ]
