# Generated by Django 5.0.7 on 2024-09-24 10:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_datacriacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuslog',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.statuslog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 10, 24, 37, 869079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('QLOUDYX', 'Qloudyx'), ('OPERADOR', 'Operador')], max_length=50),
        ),
    ]
