# Generated by Django 4.2.3 on 2024-09-25 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_statuslog_ticket_ticket_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 38, 32, 968873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('QLOUDYX', 'Qloudyx'), ('CLIENTE', 'Cliente'), ('OPERADOR', 'Operador')], max_length=50),
        ),
    ]
