# Generated by Django 4.2.3 on 2024-09-25 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_ticket_datacriacao_alter_usuarios_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 13, 39, 41, 774265, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.statuslog'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('OPERADOR', 'Operador'), ('CLIENTE', 'Cliente'), ('QLOUDYX', 'Qloudyx')], max_length=50),
        ),
    ]
