# Generated by Django 4.2.3 on 2024-09-25 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_datacriacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 35, 12, 838693, tzinfo=datetime.timezone.utc)),
        ),
    ]
