# Generated by Django 5.0.7 on 2024-09-27 10:12

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_ticket_datacriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usuario_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.usuarios_apps'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='apps_tppedidos',
            name='apps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.apps', verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='apps_tppedidos',
            name='tipoPedidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.tipospedidos', verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='peso',
            field=models.CharField(max_length=50, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 11, 58, 767402, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='app_tpPedidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.apps_tppedidos', verbose_name='Tipo de Problema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 10, 11, 58, 768401, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.statuslog', verbose_name='Estado Atual'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_Proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criador', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.prioridade', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolucao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.resolucao', verbose_name='Resolução'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='tipospedidos',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipospedidos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='date_of_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.entidades', verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/uploads/fotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin?'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Operador', 'Operador'), ('Cliente', 'Cliente')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='usuarios_apps',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.apps', verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='usuarios_apps',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
    ]
