# Generated by Django 5.0.7 on 2024-09-27 14:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_ticket_usuario_app_alter_apps_ativo_alter_apps_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 9, 17, 483677, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 9, 17, 484675, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario_app',
            field=models.ForeignKey(limit_choices_to={'is_admin': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.usuarios_apps'),
        ),
    ]
