# Generated by Django 5.0.7 on 2024-10-17 11:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_statuslog_datahora_alter_ticket_datacriacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='entidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.entidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.apps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 11, 25, 45, 905336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 11, 25, 45, 902337, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 11, 25, 45, 903338, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
    ]
