# Generated by Django 4.2.3 on 2024-10-29 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_comentario_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 15, 25, 50, 606778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 15, 25, 50, 606778, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 15, 25, 50, 605778, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.estado', verbose_name='Estado Atual'),
        ),
        migrations.CreateModel(
            name='AcaoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Texto')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('fim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fim', to='ticket.estado', verbose_name='Fim')),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inicio', to='ticket.estado', verbose_name='Inicio')),
            ],
        ),
    ]
