# Generated by Django 5.0.7 on 2024-09-27 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_alter_statuslog_datahora_alter_ticket_datacriacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 18, 29, 681521, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 14, 18, 29, 681521, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario_app',
            field=models.ForeignKey(limit_choices_to={'usuario': 'self.user'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.usuarios_apps'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Operador', 'Operador'), ('Interno', 'Interno'), ('Cliente', 'Cliente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
