# Generated by Django 4.2.3 on 2024-09-30 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_alter_statuslog_datahora_alter_ticket_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 14, 8, 18, 297976, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 14, 8, 18, 297976, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Operador', 'Operador'), ('Cliente', 'Cliente'), ('Interno', 'Interno')], max_length=50, verbose_name='Cargo'),
        ),
    ]
