# Generated by Django 4.2.3 on 2024-11-05 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_ticket_dataatualizacao_alter_comentario_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucao',
            name='tipo',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='comresolucao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 10, 53, 27, 222424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 10, 53, 27, 220918, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAtualizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 10, 53, 27, 220918, tzinfo=datetime.timezone.utc), null=True, verbose_name='Atualizado a'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 10, 53, 27, 220918, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Operador', 'Operador'), ('Interno', 'Interno'), ('Cliente', 'Cliente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
