# Generated by Django 4.2.3 on 2024-11-05 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_alter_comentario_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 11, 2, 4, 217247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 11, 2, 4, 216247, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comresolucao',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentário de Resolução'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAtualizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 11, 2, 4, 215247, tzinfo=datetime.timezone.utc), null=True, verbose_name='Atualizado a'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 11, 2, 4, 215247, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
    ]
