# Generated by Django 5.0.7 on 2024-10-09 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_alter_statuslog_datahora_alter_ticket_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 9, 36, 22, 218479, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 9, 36, 22, 219479, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='entidade',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Cliente', 'Cliente'), ('Operador', 'Operador')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='entidade',
            field=models.ManyToManyField(to='ticket.entidades', verbose_name='Entidades'),
        ),
    ]
