# Generated by Django 4.2.3 on 2024-11-11 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_alter_comentario_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 23, 0, 875062, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='dataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 23, 0, 874062, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataAtualizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 23, 0, 874062, tzinfo=datetime.timezone.utc), null=True, verbose_name='Atualizado a'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCriacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 23, 0, 874062, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Cliente', 'Cliente'), ('Operador', 'Operador')], max_length=50, verbose_name='Cargo'),
        ),
    ]
